version: "3"
services:
  broker:
    image: "eclipse-mosquitto:1.4.12"
    restart: "unless-stopped"
    ports:
          - "1883:1883"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  connector:
    image: "seraph/connector:latest"
    restart: "unless-stopped"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  io:
    network_mode: host
    image: "seraph/io:latest"
    restart: "unless-stopped"
    logging:
      driver: "json-file"
      options:
        max-size: "15m"
        max-file: "5"
  metadata:
    image: "seraph/metadata:latest"
    restart: "unless-stopped"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  locic:
    image: "seraph/logic:latest"
    restart: "unless-stopped"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
